# Generated by Django 5.0.7 on 2024-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required', null=True, verbose_name='description'),
        ),
    ]
